# Generated by Django 3.1.7 on 2021-04-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='title',
            new_name='texto',
        ),
    ]
