site_name: Tecnologias Web - Insper 2023/2
site_author: Andrew Kurauchi

extra:
  materia: Tecnologias Web
  professor: Barbara Agena
  semestre: 2023/2

theme:
  feature:
    tabs: true
  name: "material"
  palette:
    primary: "indigo"
    accent: "blue"
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: "custom_theme"

docs_dir: material
site_dir: docs

site_url: https://barbaratieko.github.io/tecweb.2023.2/

nav:
  - Home: index.md
  - Cálculo da média: notas.md
  - Aulas:
    - "01 - Get-it":
      - "Slides": "aulas/01-getit/Aula01.pdf"
      - "Handout": aulas/01-getit.md
      - "Handout Parte 1: Criando o servidor": aulas/01-getit/parte1.md
      - "Handout Parte 2: Respondendo com páginas HTML": aulas/01-getit/parte2.md
      - "Handout Parte 3: Separando algumas responsabilidades": aulas/01-getit/parte3.md
      - "Handout Parte 4: Fazendo um formulário de criação de anotação": aulas/01-getit/parte4.md
    - "02 - Desafio CSS": 
      - "Enunciado": aulas/02-desafio-css.md
      - "Slides": aulas/02-desafio-css/Aula02.pdf
    - "03 - Persistência de dados":
      - "Handout": aulas/03-persistencia-de-dados.md
      - "Handout Parte 1: Instalando o SQLite": aulas/03-persistencia-de-dados/parte1.md
      - "Handout Parte 2: Criando a tabela": aulas/03-persistencia-de-dados/parte2.md
      - "Handout Parte 3: Inserindo dados na tabela": aulas/03-persistencia-de-dados/parte3.md
      - "Handout Parte 4: Consultando e selecionando dados": aulas/03-persistencia-de-dados/parte4.md
      - "Handout Parte 5: Atualizando os dados": aulas/03-persistencia-de-dados/parte5.md
      - "Handout Parte 6: Apagando dados": aulas/03-persistencia-de-dados/parte6.md
  - Entregas:
    - "01 - ELI5": entregas/01-ELI5.md
    - "02 - Desafio CSS": aulas/02-desafio-css.md
  - Projetos:
    - "Projeto 1A": projetos/projeto1/projeto1a.md
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - markdown-enhancer.js

extra_css:
  - css/printing.css
  - css/tecweb.css

markdown_extensions:
  - markdown.extensions.tables
  - tables
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.attr_list
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: material/aulas
      check_paths: true
plugins:
  - search
  - mkdocs-video
