site_name: Tecnologias Web - Insper 2025/1
site_author: Andrew Kurauchi

extra:
  materia: Tecnologias Web
  professor: Barbara Agena
  semestre: 2025/1

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.select
    - content.tooltips
  custom_dir: overrides
  icon:
    annotation: material/arrow-right-circle

docs_dir: material
site_dir: docs

site_url: https://barbaratieko.github.io/tecweb.2025.1/

nav:
  - Home: index.md
  - Cálculo da média: notas.md
  - Aulas:
    - "01 - Get-it":
      - "Slides": "aulas/01-getit/Aula01.pdf"
      - "Handout": aulas/01-getit.md
      - "Handout Parte 1: Criando o servidor": aulas/01-getit/parte1.md
      - "Handout Parte 2: Respondendo com páginas HTML": aulas/01-getit/parte2.md
      - "Handout Parte 3: Separando algumas responsabilidades": aulas/01-getit/parte3.md
      - "Handout Parte 4: Fazendo um formulário de criação de anotação": aulas/01-getit/parte4.md
    - "02 - Desafio CSS": 
      - "Slides": "aulas/02-desafio-css/Aula02.pdf"
      - "Enunciado": aulas/02-desafio-css.md
  - "Material Auxiliar":
    - "Usando Python com ambientes virtuais": auxiliar/venv.md
    - "Guia de Instalação WSL e Docker para Windows": https://github.com/InsperGuides/Guia-Instalacao-WSL-e-Docker---Windows
  - Entregas:
    - "01 - ELI5": entregas/01-ELI5.md
    - "02 - Desafio CSS": aulas/02-desafio-css.md
  
markdown_extensions:
  - abbr
  - tables
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: material/aulas
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


    

 
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/progress-check.js
  - javascripts/quiz.js
  - javascripts/short-questions.js
  - javascripts/translate-admonitions.js
  - javascripts/webhook-config.js


extra_css:
  - css/printing.css
  - css/tecweb.css

plugins:
  - search
  - glightbox

watch:
  - includes